force-app/main/default/objects/Demo__c/Demo__c.object-meta.xml
<CustomObject>
    <label>Demo</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app-test/main/default/classes/DemoControllerTest.cls
@IsTest
private class DemoControllerTest {
  @IsTest
  static void getDemos() {
    Profile p = TestUtility.getStandardProfile();
    User u = TestUtility.createDemoUser(p);
    TestUtility.assignPermission(u, 'demo');

    System.runAs(u) {
      List<Demo__c> records = new List<Demo__c>{
        new Demo__c(Name = 'Foo'),
        new Demo__c(Name = 'Bar', description__c = 'Bar Description')
      };
      insert records;

      Test.startTest();

      List<DemoController.Demo> actual = DemoController.getDemos();

      System.assertEquals(2, actual.size());

      DemoController.Demo actualThat = actual.get(0);
      System.assertEquals(true, actualThat.id != null);
      System.assertEquals('Bar', actualThat.name);
      System.assertEquals('Bar Description', actualThat.description);

      actualThat = actual.get(1);
      System.assertEquals(true, actualThat.id != null);
      System.assertEquals('Foo', actualThat.name);
      System.assertEquals(null, actualThat.description);

      Test.stopTest();
    }

  }
}