force-app/main/default/objects/demo_api_setting__c/demo_api_setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DemoApiSetting</label>
</CustomObject>

force-app/main/default/objects/demo_api_setting__c/fields/api_key__c.field-meta.xml
<CustomField>
    <fullName>api_key__c</fullName>
    <label>ApiKey</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DemoApiSettingRepository.cls
public with sharing class DemoApiSettingRepository {
  public void register(DemoApiSetting entity) {
    demo_api_setting__c target = demo_api_setting__c.getOrgDefaults();
    target.api_key__c = entity.apiKey;
    upsert target;
  }

  public with sharing class DemoApiSetting {
    public String apiKey { get; private set; }

    public DemoApiSetting(String apiKey) {
      this.apiKey = apiKey;
    }
  }
}