force-app/main/default/objects/api_config__mdt/api_config__mdt.object-meta.xml
<CustomObject>
    <label>ApiConfig</label>
</CustomObject>

force-app/main/default/objects/api_config__mdt/fields/host__c.field-meta.xml
<CustomField>
    <fullName>host__c</fullName>
    <label>host</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/demo_api_setting__c/demo_api_setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DemoApiSetting</label>
</CustomObject>

force-app/main/default/objects/demo_api_setting__c/fields/api_key__c.field-meta.xml
<CustomField>
    <fullName>api_key__c</fullName>
    <label>ApiKey</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DemoApi.cls
public with sharing virtual class DemoApi {
  public virtual Contract getContract() {
    api_config__mdt apiConfig = api_config__mdt.getInstance('demo_api');
    String endpoint = apiConfig.host__c + '/contract';

    demo_api_setting__c demoApiSetting = demo_api_setting__c.getOrgDefaults();
    if (demoApiSetting.api_key__c == null) {
      throw new UnauthorizedException.NotSetApiKeyException();
    }

    Http http = new Http();

    HttpRequest request = new HttpRequest();
    request.setEndpoint(endpoint);
    request.setMethod('GET');
    request.setHeader('Accept', 'application/json');
    request.setHeader('api-key', demoApiSetting.api_key__c);
    request.setHeader('organization-id', UserInfo.getOrganizationId());

    HttpResponse response = http.send(request);
    switch on response.getStatusCode() {
      when 200 {
        return (Contract) JSON.deserialize(response.getBody(), Contract.class);
      }
      when 401 {
        throw new UnauthorizedException(response.getBody());
      }
      when else {
        throw new ApiException(
          'unexpected server error',
          response.getStatusCode(),
          response.getBody()
        );
      }
    }
  }

  public class Contract {
    public String id { get; private set; }
    public String name { get; private set; }

    public Contract(String id, String name) {
      this.id = id;
      this.name = name;
    }
  }
}